<?php
/**
 * NUCLEAR FIX - Evaluasi path secara langsung, bukan pakai regex
 */
set_time_limit(60);
error_reporting(E_ALL);
ini_set('display_errors', 1);

echo "<html><head><title>Nuclear Fix</title><style>
body{font-family:sans-serif;background:#0f172a;color:#e2e8f0;padding:40px;max-width:700px;margin:auto;}
.ok{color:#4ade80;font-weight:bold;} .err{color:#f87171;font-weight:bold;}
h2{color:#38bdf8;} code{background:#1e293b;padding:2px 6px;border-radius:4px;font-size:11px;}
</style></head><body>";

echo "<h2>☢️ Nuclear Autoloader Fix</h2>";

$vendorDir = dirname(__DIR__) . '/vendor';
$composerDir = $vendorDir . '/composer';

// ============================================================
// STEP 1: Fix autoload_files.php
// File ini berisi array path-path yang harus di-require
// ============================================================
echo "<h3>Step 1: Fix autoload_files.php</h3>";

$filesPath = $composerDir . '/autoload_files.php';
if (file_exists($filesPath)) {
    // Include file untuk mendapatkan array-nya
    $vendorDir_backup = $vendorDir; // simpan
    $baseDir = dirname($vendorDir);
    $files = require $filesPath;
    
    if (is_array($files)) {
        $newEntries = [];
        $removed = 0;
        
        foreach ($files as $hash => $path) {
            if (file_exists($path)) {
                $newEntries[$hash] = $path;
            } else {
                $shortPath = str_replace(dirname(__DIR__) . '/', '', $path);
                echo "<p>🗑️ Hapus: <code>$shortPath</code></p>";
                $removed++;
            }
        }
        
        // Tulis ulang file
        $output = "<?php\n\n// autoload_files.php @generated by Composer (FIXED)\n\n";
        $output .= "\$vendorDir = dirname(__DIR__);\n";
        $output .= "\$baseDir = dirname(\$vendorDir);\n\n";
        $output .= "return array(\n";
        foreach ($newEntries as $hash => $path) {
            // Konversi absolute path kembali ke relative
            $relativePath = str_replace($vendorDir, '$vendorDir . \'', $path);
            $relativePath = str_replace($baseDir, '$baseDir . \'', $relativePath);
            if (strpos($relativePath, '$') === 0) {
                $relativePath .= "'";
                $output .= "    '$hash' => $relativePath,\n";
            } else {
                $output .= "    '$hash' => '$path',\n";
            }
        }
        $output .= ");\n";
        
        file_put_contents($filesPath, $output);
        echo "<p class='ok'>✅ autoload_files.php: $removed file hilang dihapus</p>";
    } else {
        echo "<p class='err'>Format tidak dikenali</p>";
    }
} else {
    echo "<p>File tidak ada, skip.</p>";
}

// ============================================================
// STEP 2: Fix autoload_static.php - bagian $files
// ============================================================
echo "<h3>Step 2: Fix autoload_static.php</h3>";

$staticPath = $composerDir . '/autoload_static.php';
if (file_exists($staticPath)) {
    $content = file_get_contents($staticPath);
    
    // Cari blok public static $files = array(...)
    // Kita perlu mengevaluasi setiap path di dalamnya
    // Caranya: baca setiap baris, evaluasi path, cek exists
    
    $lines = explode("\n", $content);
    $newLines = [];
    $inFilesBlock = false;
    $removedStatic = 0;
    
    foreach ($lines as $line) {
        // Deteksi awal blok $files
        if (preg_match('/public\s+static\s+\$files\s*=\s*array\s*\(/', $line)) {
            $inFilesBlock = true;
            $newLines[] = $line;
            continue;
        }
        
        if ($inFilesBlock) {
            // Deteksi akhir blok
            if (trim($line) === ');') {
                $inFilesBlock = false;
                $newLines[] = $line;
                continue;
            }
            
            // Evaluasi path di baris ini
            // Format: 'hash' => __DIR__ . '/..' . '/path/to/file.php',
            if (preg_match("/'[a-f0-9]+'\\s*=>\\s*(.+),?$/", trim($line), $m)) {
                $pathExpr = rtrim($m[1], ',');
                // Ganti __DIR__ dengan path sebenarnya
                $evalPath = str_replace('__DIR__', "'" . $composerDir . "'", $pathExpr);
                $evalPath = str_replace("' . '", "", $evalPath); // gabungkan string
                $evalPath = trim($evalPath, "'\"");
                
                // Resolve path
                $resolvedPath = realpath($evalPath);
                if (!$resolvedPath) {
                    // Coba manual resolve
                    $resolvedPath = $evalPath;
                    // Replace /./ and resolve /../
                    while (strpos($resolvedPath, '/./') !== false) {
                        $resolvedPath = str_replace('/./', '/', $resolvedPath);
                    }
                    while (preg_match('#/[^/]+/\.\./#', $resolvedPath)) {
                        $resolvedPath = preg_replace('#/[^/]+/\.\./#', '/', $resolvedPath);
                    }
                }
                
                if (!file_exists($resolvedPath) && !file_exists($evalPath)) {
                    $shortPath = basename(dirname(dirname($resolvedPath))) . '/.../' . basename($resolvedPath);
                    echo "<p>🗑️ Hapus dari static: <code>$shortPath</code></p>";
                    $removedStatic++;
                    continue; // Skip baris ini
                }
            }
            
            $newLines[] = $line;
            continue;
        }
        
        $newLines[] = $line;
    }
    
    if ($removedStatic > 0) {
        file_put_contents($staticPath, implode("\n", $newLines));
        echo "<p class='ok'>✅ autoload_static.php: $removedStatic entry dihapus</p>";
    } else {
        echo "<p>Tidak ada perubahan di static (mungkin sudah bersih).</p>";
    }
}

// ============================================================
// STEP 3: Test autoload
// ============================================================
echo "<h3>Step 3: Test</h3>";

// Clear opcode cache
if (function_exists('opcache_reset')) @opcache_reset();

try {
    require_once $vendorDir . '/autoload.php';
    echo "<p class='ok'>✅ BERHASIL! Autoloader dimuat tanpa error!</p>";
    echo "<h2 class='ok'>🎉 WEB SUDAH NORMAL!</h2>";
    echo "<p><a href='/' style='color:#38bdf8;font-weight:bold;font-size:20px;text-decoration:underline;'>← BUKA HALAMAN UTAMA</a></p>";
    
    // Cleanup semua script fix
    @unlink(__FILE__);
    @unlink(dirname(__FILE__) . '/restore_autoloader.php');
    @unlink(dirname(__FILE__) . '/fix_vendor.php');
} catch (Throwable $e) {
    echo "<p class='err'>❌ Masih error: " . htmlspecialchars($e->getMessage()) . "</p>";
    echo "<p><a href='' style='color:#38bdf8;font-weight:bold;'>🔄 Klik refresh (jalankan 1x lagi)</a></p>";
}

echo "</body></html>";
